# Generated by Django 5.1.15 on 2026-06-08 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockListEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('kind', models.CharField(choices=[('sender_email', 'Block-list sender (exact email)'), ('sender_domain', 'Block-list domain (e.g. *@newsletter.xyz)'), ('marketing', 'Marketing / bulk header'), ('noreply', 'No-reply / automated pattern'), ('internal', 'Internal address'), ('spam', 'Spam / phishing pattern')], max_length=20)),
                ('value', models.CharField(help_text='Email, domain pattern, or header/regex token to match.', max_length=255)),
                ('note', models.CharField(blank=True, default='', max_length=255)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='block_list', to='organizations.brand')),
            ],
            options={
                'verbose_name_plural': 'block list entries',
                'ordering': ['kind', 'value'],
            },
        ),
        migrations.CreateModel(
            name='BrandSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ai_provider', models.CharField(choices=[('gemini', 'Gemini'), ('chatgpt', 'ChatGPT')], default='gemini', max_length=20)),
                ('ai_api_key', models.CharField(blank=True, default='', max_length=255)),
                ('ai_model', models.CharField(blank=True, default='', max_length=100)),
                ('confidence_threshold', models.FloatField(default=0.75)),
                ('automation_toggles', models.JSONField(blank=True, default=dict)),
                ('await_evidence_autosend', models.BooleanField(default=True)),
                ('holding_reply', models.TextField(default='Our team will review and get back to you shortly.')),
                ('sla_config', models.JSONField(blank=True, default=dict)),
                ('brand', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='organizations.brand')),
            ],
            options={
                'verbose_name_plural': 'brand settings',
            },
        ),
    ]
