# Generated by Django 5.1.15 on 2026-06-08 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_settings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='brandsettings',
            name='integrations',
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
