# Generated by Django 5.1.15 on 2026-06-09 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_settings', '0002_brandsettings_integrations'),
    ]

    operations = [
        migrations.AlterField(
            model_name='brandsettings',
            name='ai_provider',
            field=models.CharField(choices=[('gemini', 'Gemini'), ('chatgpt', 'ChatGPT'), ('groq', 'Groq (Llama)')], default='gemini', max_length=20),
        ),
    ]
