# Generated by Django 5.1.15 on 2026-06-27 04:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_settings', '0003_alter_brandsettings_ai_provider'),
        ('organizations', '0004_userauditlog'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('email', models.EmailField(help_text="Support inbox or 'send mail as' alias.", max_length=254)),
                ('display_name', models.CharField(blank=True, default='', max_length=200)),
                ('is_primary', models.BooleanField(default=False, help_text='The ONE Gmail inbox actually fetched. Aliases are sending-only.')),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='support_emails', to='organizations.brand')),
            ],
            options={
                'ordering': ['-is_primary', 'email'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'email'), name='uniq_brand_support_email')],
            },
        ),
    ]
