# Generated by Django 5.1.15 on 2026-06-27 04:29

from django.db import migrations


def seed_primary(apps, schema_editor):
    """Auto-insert each brand's current fetched mailbox as its PRIMARY support email so existing
    systems keep working with no manual setup. Aliases are added later from Settings."""
    Mailbox = apps.get_model("organizations", "Mailbox")
    SupportEmail = apps.get_model("brand_settings", "SupportEmail")
    for mb in Mailbox.objects.all():
        email = (mb.email_address or "").strip().lower()
        if not email:
            continue
        SupportEmail.objects.get_or_create(
            brand_id=mb.brand_id, email=email,
            defaults={"display_name": "Primary", "is_primary": True, "is_active": True},
        )


def unseed(apps, schema_editor):
    apps.get_model("brand_settings", "SupportEmail").objects.filter(is_primary=True).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('brand_settings', '0004_supportemail'),
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(seed_primary, unseed),
    ]
