# Generated by Django 5.1.15 on 2026-06-27 05:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brand_settings', '0005_seed_primary_support_emails'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportemail',
            name='owner_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
    ]
