# Generated by Django 5.1.15 on 2026-06-26 05:25

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0004_userauditlog'),
        ('tickets', '0021_escalation_assigned_at_escalation_assigned_to_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('last_active_at', models.DateTimeField(blank=True, null=True)),
                ('employee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='activity', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_activity',
            },
        ),
        migrations.CreateModel(
            name='EmployeeLoginHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('login_at', models.DateTimeField(blank=True, null=True)),
                ('logout_at', models.DateTimeField(blank=True, null=True)),
                ('session_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('ip_address', models.CharField(blank=True, default='', max_length=64)),
                ('device', models.CharField(blank=True, default='', max_length=120)),
                ('browser', models.CharField(blank=True, default='', max_length=200)),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='login_history', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'employee_login_history',
                'ordering': ['-login_at'],
            },
        ),
        migrations.CreateModel(
            name='AutoReplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('template', models.CharField(blank=True, default='', max_length=120)),
                ('trigger', models.CharField(blank=True, default='', max_length=120)),
                ('ticket_ref', models.CharField(blank=True, default='', max_length=60)),
                ('execution_ms', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('status', models.CharField(blank=True, default='sent', max_length=40)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.brand')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='auto_reply_logs', to='tickets.ticket')),
            ],
            options={
                'db_table': 'auto_reply_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'created_at'], name='auto_reply__brand_i_3afa80_idx')],
            },
        ),
        migrations.CreateModel(
            name='DashboardDailyStats',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('day', models.DateField()),
                ('emails_received', models.PositiveIntegerField(default=0)),
                ('tickets_created', models.PositiveIntegerField(default=0)),
                ('tickets_resolved', models.PositiveIntegerField(default=0)),
                ('auto_replies', models.PositiveIntegerField(default=0)),
                ('manual_replies', models.PositiveIntegerField(default=0)),
                ('escalations', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.brand')),
            ],
            options={
                'db_table': 'dashboard_daily_stats',
                'ordering': ['-day'],
                'constraints': [models.UniqueConstraint(fields=('brand', 'day'), name='uniq_brand_day')],
            },
        ),
        migrations.CreateModel(
            name='ManualReplyLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('employee_name', models.CharField(blank=True, default='', max_length=200)),
                ('employee_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('ticket_ref', models.CharField(blank=True, default='', max_length=60)),
                ('reply_size', models.PositiveIntegerField(default=0)),
                ('attachments', models.PositiveIntegerField(default=0)),
                ('response_seconds', models.PositiveIntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, default='sent', max_length=40)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.brand')),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('escalation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_reply_logs', to='tickets.escalation')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='organizations.organization')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='manual_reply_logs', to='tickets.ticket')),
            ],
            options={
                'db_table': 'manual_reply_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'created_at'], name='manual_repl_brand_i_4ac683_idx'), models.Index(fields=['employee_email'], name='manual_repl_employe_40a41e_idx')],
            },
        ),
    ]
