# Generated by Django 5.1.15 on 2026-06-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('analytics', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='manualreplylog',
            name='sender_email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
