# Generated by Django 5.1.15 on 2026-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailbox',
            name='imap_last_uid',
            field=models.BigIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='mailbox',
            name='imap_uidvalidity',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
