# Generated by Django 5.1.15 on 2026-06-08 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="e.g. '3'", max_length=10)),
                ('name', models.CharField(max_length=200)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='organizations.brand')),
            ],
            options={
                'verbose_name_plural': 'categories',
                'ordering': ['position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='SubTopic',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('code', models.CharField(help_text="e.g. '3.3'", max_length=10)),
                ('name', models.CharField(max_length=255)),
                ('question', models.TextField(blank=True, default='')),
                ('mandatory_inputs', models.JSONField(blank=True, default=list)),
                ('is_sensitive', models.BooleanField(default=False)),
                ('position', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sub_topics', to='taxonomy.category')),
            ],
            options={
                'ordering': ['position', 'code'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('condition', models.TextField(blank=True, default='', help_text='The IF condition (engine logic)')),
                ('then_response', models.TextField(blank=True, default='', help_text='The THEN response sent / drafted')),
                ('action', models.CharField(choices=[('info_only', 'Info only (auto-send)'), ('await_evidence', 'Await evidence (auto-send template)'), ('create_ticket', 'Create Ticket (draft only)'), ('update_system', 'Update in system (agent action)'), ('continue_check', 'Continue to next check'), ('trigger_cancellation_refund_pickup', 'Trigger cancellation / refund / pickup (agent action)')], default='create_ticket', max_length=50)),
                ('position', models.PositiveIntegerField(default=0, help_text='Evaluation order within the sub-topic')),
                ('is_active', models.BooleanField(default=True)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rules', to='taxonomy.subtopic')),
            ],
            options={
                'ordering': ['sub_topic', 'position'],
            },
        ),
        migrations.CreateModel(
            name='Template',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(default='default', max_length=120)),
                ('body', models.TextField(help_text='Supports placeholders like {order_id}, {tracking_url}, {edd}.')),
                ('is_active', models.BooleanField(default=True)),
                ('sub_topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='templates', to='taxonomy.subtopic')),
            ],
            options={
                'ordering': ['sub_topic', 'name'],
            },
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('brand', 'code'), name='uniq_category_code_per_brand'),
        ),
        migrations.AddConstraint(
            model_name='subtopic',
            constraint=models.UniqueConstraint(fields=('category', 'code'), name='uniq_subtopic_code_per_category'),
        ),
        migrations.AddConstraint(
            model_name='template',
            constraint=models.UniqueConstraint(fields=('sub_topic', 'name'), name='uniq_template_name_per_subtopic'),
        ),
    ]
