# Generated by Django 5.1.15 on 2026-06-10 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='requires_evidence',
            field=models.BooleanField(default=False),
        ),
    ]
