# Generated by Django 5.1.15 on 2026-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0002_subtopic_requires_evidence'),
    ]

    operations = [
        migrations.AddField(
            model_name='subtopic',
            name='requires_video',
            field=models.BooleanField(default=False),
        ),
    ]
