# Generated by Django 5.1.15 on 2026-06-11 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taxonomy', '0003_subtopic_requires_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='requires_video',
            field=models.BooleanField(default=False),
        ),
    ]
