# Generated by Django 5.1.15 on 2026-06-08 07:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('organizations', '0001_initial'),
        ('taxonomy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('ticket_id', models.CharField(db_index=True, max_length=40, unique=True)),
                ('thread_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('sub_topic', models.CharField(blank=True, default='', max_length=255)),
                ('action_taken', models.CharField(blank=True, default='', max_length=200)),
                ('status', models.CharField(choices=[('new', 'New'), ('classified', 'Classified'), ('auto_resolved', 'Auto-Resolved'), ('awaiting_evidence', 'Awaiting Evidence'), ('awaiting_agent', 'Awaiting Agent'), ('in_progress', 'In Progress'), ('escalated', 'Escalated'), ('resolved', 'Resolved'), ('closed', 'Closed'), ('ignored', 'Ignored')], db_index=True, default='new', max_length=30)),
                ('priority', models.CharField(choices=[('high', 'High'), ('normal', 'Normal'), ('low', 'Low')], db_index=True, default='normal', max_length=10)),
                ('ai_confidence', models.FloatField(blank=True, null=True)),
                ('ai_handled', models.BooleanField(default=False)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('sentiment', models.CharField(blank=True, default='', max_length=30)),
                ('mandatory_inputs', models.JSONField(blank=True, default=list)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('is_ignored', models.BooleanField(default=False)),
                ('ignored_reason', models.CharField(blank=True, default='', max_length=255)),
                ('sla_due_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='organizations.brand')),
                ('category_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='taxonomy.category')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='organizations.mailbox')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='organizations.organization')),
                ('sub_topic_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tickets', to='taxonomy.subtopic')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('direction', models.CharField(choices=[('inbound', 'Inbound (from customer)'), ('outbound', 'Outbound (reply)')], default='inbound', max_length=10)),
                ('gmail_message_id', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('references', models.JSONField(blank=True, default=list)),
                ('from_email', models.EmailField(blank=True, default='', max_length=254)),
                ('to_email', models.CharField(blank=True, default='', max_length=500)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('is_draft', models.BooleanField(default=False)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='tickets.ticket')),
            ],
            options={
                'ordering': ['created_at'],
            },
        ),
        migrations.CreateModel(
            name='AuditLogEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('actor', models.CharField(default='system', help_text="username, 'ai', or 'system'", max_length=120)),
                ('event', models.CharField(max_length=120)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('ticket', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_log', to='tickets.ticket')),
            ],
            options={
                'verbose_name_plural': 'audit log entries',
                'ordering': ['created_at'],
            },
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['brand', 'status'], name='tickets_tic_brand_i_ecc157_idx'),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['brand', 'is_ignored'], name='tickets_tic_brand_i_6235e1_idx'),
        ),
    ]
