# Generated by Django 5.1.15 on 2026-06-09 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0002_ticket_resolved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ai_attempts',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='ticket',
            name='ai_error',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='ticket',
            name='classification_status',
            field=models.CharField(choices=[('PENDING_AI', 'Pending AI'), ('AI_PROCESSING', 'AI Processing'), ('AI_CLASSIFIED', 'AI Classified'), ('AI_FAILED', 'AI Failed')], db_index=True, default='PENDING_AI', max_length=20),
        ),
    ]
