# Generated by Django 5.1.15 on 2026-06-09 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0003_ticket_ai_attempts_ticket_ai_error_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='imap_uid',
            field=models.BigIntegerField(blank=True, db_index=True, null=True),
        ),
    ]
