# Generated by Django 5.1.15 on 2026-06-09 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0004_message_imap_uid'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='issue_summary',
            field=models.TextField(blank=True, default=''),
        ),
    ]
