# Generated by Django 5.1.15 on 2026-06-10 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0006_attachment'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='pending_evidence',
            field=models.BooleanField(default=False),
        ),
    ]
