# Generated by Django 5.1.15 on 2026-06-10 07:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0002_mailbox_imap_last_uid_mailbox_imap_uidvalidity'),
        ('taxonomy', '0001_initial'),
        ('tickets', '0007_ticket_pending_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='PendingConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('order_id', models.CharField(blank=True, default='', max_length=60)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('original_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('last_message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('thread_id', models.CharField(blank=True, default='', max_length=255)),
                ('in_reply_to', models.CharField(blank=True, default='', max_length=255)),
                ('references', models.JSONField(blank=True, default=list)),
                ('headers', models.JSONField(blank=True, default=dict)),
                ('body_text', models.TextField(blank=True, default='')),
                ('body_html', models.TextField(blank=True, default='')),
                ('category', models.CharField(blank=True, default='', max_length=200)),
                ('sub_topic', models.CharField(blank=True, default='', max_length=255)),
                ('issue_summary', models.TextField(blank=True, default='')),
                ('confidence', models.FloatField(blank=True, null=True)),
                ('sentiment', models.CharField(blank=True, default='', max_length=30)),
                ('language', models.CharField(blank=True, default='', max_length=10)),
                ('requires_agent', models.BooleanField(default=False)),
                ('extracted', models.JSONField(blank=True, default=dict)),
                ('evidence_requests', models.PositiveIntegerField(default=0)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_conversations', to='organizations.brand')),
                ('category_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_conversations', to='taxonomy.category')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_conversations', to='organizations.mailbox')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pending_conversations', to='organizations.organization')),
                ('sub_topic_ref', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_conversations', to='taxonomy.subtopic')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'customer_email'], name='tickets_pen_brand_i_607b23_idx')],
            },
        ),
    ]
