# Generated by Django 5.1.15 on 2026-06-10 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0008_pendingconversation'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='ticket_number',
            field=models.CharField(blank=True, default='', max_length=60),
        ),
        migrations.AddField(
            model_name='ticket',
            name='tracking_url',
            field=models.URLField(blank=True, default='', max_length=500),
        ),
    ]
