# Generated by Django 5.1.15 on 2026-06-10 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0009_ticket_ticket_number_ticket_tracking_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='remote_url',
            field=models.URLField(blank=True, default='', max_length=600),
        ),
    ]
