# Generated by Django 5.1.15 on 2026-06-11 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0010_attachment_remote_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingconversation',
            name='status',
            field=models.CharField(blank=True, default='awaiting_evidence', max_length=40),
        ),
    ]
