# Generated by Django 5.1.15 on 2026-06-11 08:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0011_pendingconversation_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='sha256',
            field=models.CharField(blank=True, db_index=True, default='', max_length=64),
        ),
    ]
