# Generated by Django 5.1.15 on 2026-06-12 04:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0012_attachment_sha256'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='pending',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.pendingconversation'),
        ),
        migrations.AddField(
            model_name='pendingconversation',
            name='has_evidence',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='pendingconversation',
            name='has_video',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='attachment',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.ticket'),
        ),
    ]
