# Generated by Django 5.1.15 on 2026-06-12 05:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0013_attachment_pending_pendingconversation_has_evidence_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingconversation',
            name='has_photo',
            field=models.BooleanField(default=False),
        ),
    ]
