# Generated by Django 5.1.15 on 2026-06-12 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0015_pendingconversation_closed_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pendingconversation',
            name='requires_evidence',
            field=models.BooleanField(default=True),
        ),
    ]
