# Generated by Django 5.1.15 on 2026-06-12 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0016_pendingconversation_requires_evidence'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pendingconversation',
            name='requires_evidence',
            field=models.BooleanField(db_default=True, default=True),
        ),
    ]
