# Generated by Django 5.1.15 on 2026-06-20 05:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_userauditlog'),
        ('tickets', '0017_alter_pendingconversation_requires_evidence'),
    ]

    operations = [
        migrations.CreateModel(
            name='Inquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('inquiry_type', models.CharField(choices=[('FRANCHISEE', 'Franchisee'), ('DROPSHIPPING', 'Dropshipping'), ('COMPANY_PROFILE', 'Company Profile'), ('INVOICE_REQUEST', 'Invoice Request'), ('OTHER_INQUIRY', 'Other Inquiry')], db_index=True, max_length=30)),
                ('channel', models.CharField(default='email', max_length=20)),
                ('status', models.CharField(choices=[('in_progress', 'In Progress'), ('completed', 'Completed')], db_index=True, default='in_progress', max_length=20)),
                ('queue', models.CharField(blank=True, default='', max_length=40)),
                ('customer_email', models.EmailField(blank=True, default='', max_length=254)),
                ('customer_name', models.CharField(blank=True, default='', max_length=200)),
                ('phone', models.CharField(blank=True, default='', max_length=30)),
                ('data', models.JSONField(blank=True, default=dict)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='organizations.brand')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='organizations.mailbox')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inquiries', to='organizations.organization')),
                ('pending', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inquiries', to='tickets.pendingconversation')),
            ],
            options={
                'verbose_name_plural': 'inquiries',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'inquiry_type', 'status'], name='tickets_inq_brand_i_262702_idx')],
            },
        ),
    ]
