# Generated by Django 5.1.15 on 2026-06-25 13:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_userauditlog'),
        ('tickets', '0018_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Escalation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.EmailField(blank=True, default='', max_length=254)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('matched_keyword', models.CharField(blank=True, default='', max_length=60)),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('manual_review_required', 'Manual Review Required'), ('ticket_created', 'Ticket Created'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='manual_review_required', max_length=30)),
                ('priority', models.CharField(default='high', max_length=10)),
                ('queue', models.CharField(db_index=True, default='escalation', max_length=40)),
                ('resolved_at', models.DateTimeField(blank=True, null=True)),
                ('resolved_by', models.CharField(blank=True, default='', max_length=120)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='organizations.brand')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='organizations.mailbox')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='escalations', to='organizations.organization')),
                ('ticket', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='escalations', to='tickets.ticket')),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['brand', 'status', 'queue'], name='tickets_esc_brand_i_6fa471_idx')],
            },
        ),
    ]
