# Generated by Django 5.1.15 on 2026-06-26 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0019_escalation'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='conversation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='escalation',
            name='references',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='escalation',
            name='thread_ids',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='status',
            field=models.CharField(choices=[('manual_review_required', 'Manual Review Required'), ('awaiting_customer_reply', 'Awaiting Customer Reply'), ('ticket_created', 'Ticket Created'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='manual_review_required', max_length=30),
        ),
    ]
