# Generated by Django 5.1.15 on 2026-06-26 04:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0020_escalation_conversation_escalation_references_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='escalation',
            name='assigned_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='escalation',
            name='assigned_to',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120),
        ),
        migrations.AddField(
            model_name='escalation',
            name='attachments',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='escalation',
            name='draft',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='escalation',
            name='is_read',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='escalation',
            name='sender_name',
            field=models.CharField(blank=True, default='', max_length=200),
        ),
        migrations.AddField(
            model_name='escalation',
            name='timeline',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='escalation',
            name='status',
            field=models.CharField(choices=[('manual_review_required', 'Manual Review Required'), ('awaiting_customer_reply', 'Awaiting Customer Reply'), ('pending', 'Pending'), ('ticket_created', 'Converted to Ticket'), ('resolved', 'Resolved'), ('ignored', 'Ignored')], db_index=True, default='manual_review_required', max_length=30),
        ),
    ]
