# Generated by Django 5.1.15 on 2026-06-26 06:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0021_escalation_assigned_at_escalation_assigned_to_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attachment',
            name='escalation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reply_attachments', to='tickets.escalation'),
        ),
    ]
