# Generated by Django 5.1.15 on 2026-06-26 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_userauditlog'),
        ('tickets', '0022_attachment_escalation'),
    ]

    operations = [
        migrations.CreateModel(
            name='InternalEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('sender', models.EmailField(blank=True, default='', max_length=254)),
                ('sender_name', models.CharField(blank=True, default='', max_length=200)),
                ('to_addrs', models.JSONField(blank=True, default=list)),
                ('matched_recipient', models.CharField(blank=True, default='', max_length=255)),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body', models.TextField(blank=True, default='')),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=255)),
                ('received_at', models.DateTimeField(blank=True, null=True)),
                ('status', models.CharField(choices=[('internal_review', 'Internal Review'), ('awaiting_reply', 'Awaiting Reply'), ('archived', 'Archived'), ('deleted', 'Deleted')], db_index=True, default='internal_review', max_length=30)),
                ('priority', models.CharField(default='normal', max_length=10)),
                ('is_read', models.BooleanField(db_index=True, default=False)),
                ('assigned_to', models.CharField(blank=True, db_index=True, default='', max_length=120)),
                ('assigned_at', models.DateTimeField(blank=True, null=True)),
                ('draft', models.TextField(blank=True, default='')),
                ('conversation', models.JSONField(blank=True, default=list)),
                ('thread_ids', models.JSONField(blank=True, default=list)),
                ('references', models.JSONField(blank=True, default=list)),
                ('timeline', models.JSONField(blank=True, default=list)),
                ('attachments', models.JSONField(blank=True, default=list)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_emails', to='organizations.brand')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internal_emails', to='organizations.mailbox')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='internal_emails', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='internal_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='email_attachments', to='tickets.internalemail'),
        ),
        migrations.AddIndex(
            model_name='internalemail',
            index=models.Index(fields=['brand', 'status'], name='tickets_int_brand_i_a62058_idx'),
        ),
    ]
