# Generated by Django 5.1.15 on 2026-07-03 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_userauditlog'),
        ('tickets', '0023_internalemail_attachment_internal_email_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComposedEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_email', models.CharField(blank=True, default='', max_length=255)),
                ('to_addrs', models.TextField(blank=True, default='')),
                ('cc', models.TextField(blank=True, default='')),
                ('bcc', models.TextField(blank=True, default='')),
                ('subject', models.CharField(blank=True, default='', max_length=500)),
                ('body_html', models.TextField(blank=True, default='')),
                ('body_text', models.TextField(blank=True, default='')),
                ('status', models.CharField(choices=[('draft', 'Draft'), ('sent', 'Sent'), ('failed', 'Failed')], db_index=True, default='draft', max_length=10)),
                ('message_id', models.CharField(blank=True, default='', max_length=255)),
                ('error', models.TextField(blank=True, default='')),
                ('created_by', models.CharField(blank=True, default='', max_length=150)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composed_emails', to='organizations.brand')),
                ('mailbox', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composed_emails', to='organizations.mailbox')),
                ('organization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='composed_emails', to='organizations.organization')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='attachment',
            name='composed_email',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='tickets.composedemail'),
        ),
        migrations.AddIndex(
            model_name='composedemail',
            index=models.Index(fields=['brand', 'status'], name='tickets_com_brand_i_7e8b99_idx'),
        ),
    ]
