# Generated by Django 5.1.15 on 2026-07-03 10:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0024_composedemail_attachment_composed_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='composedemail',
            name='conversation',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='composedemail',
            name='is_read',
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AddField(
            model_name='composedemail',
            name='thread_refs',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='composedemail',
            name='ticket',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='composed_emails', to='tickets.ticket'),
        ),
    ]
