# Generated by Django 5.1.15 on 2026-07-03 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('organizations', '0004_userauditlog'),
        ('taxonomy', '0004_category_requires_video'),
        ('tickets', '0025_composedemail_conversation_composedemail_is_read_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='ticket',
            name='agent_unread',
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name='ticket',
            name='last_activity_at',
            field=models.DateTimeField(blank=True, db_index=True, null=True),
        ),
        migrations.AddIndex(
            model_name='ticket',
            index=models.Index(fields=['brand', 'last_activity_at'], name='tickets_tic_brand_i_2d75ba_idx'),
        ),
    ]
